version: "0.5"

processes:
  pnpm:
    command: pnpm install --frozen-lockfile

  php:
    command: php artisan serve

  laravel_logs:
    command: tail -f storage/logs/laravel.log
    restart: always

  vite:
    command: pnpm dev
    depends_on:
      pnpm:
        condition: process_completed_successfully
